// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package algo2UML.Clients;

import algo2UML.Server.DataClass1;

/************************************************************/
/**
 * 
 */
public class Client1 {
	/**
	 * 
	 */
	public String Attribute2;
	/**
	 * 
	 */
	public int Attribute4;
	/**
	 * 
	 */
	public DataClass1 Attribute5;
}
