// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package algo2UML.Clients;

/************************************************************/
/**
 * 
 */
public class ClientRoot {
	/**
	 * 
	 */
	public Client1 client1;
	/**
	 * 
	 */
	public Client2 client2;
}
