// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package algo2UML.Clients;

/************************************************************/
/**
 * 
 */
public class Client2 extends Client1 {
	/**
	 * 
	 */
	public int Attribute3;
}
