// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package algo2UML.Server;

/************************************************************/
/**
 * 
 */
public class DataClass1 {
	/**
	 * 
	 */
	public int Field1;
	/**
	 * 
	 */
	public int Field2;
	/**
	 * 
	 */
	public String Field3;
	/**
	 * 
	 */
	public String Field4;
}
