// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package algo2UML.Server;

/************************************************************/
/**
 * 
 */
public class Server1 {
	/**
	 * 
	 */
	public DataClass1 Attribute1;

	/**
	 * 
	 * @return 
	 */
	private int service1() {
		return 0;
	}
}
